bankVaultsImage: banzaicloud/bank-vaults:1.14.3

existingTlsSecretName: ""

image: vault:1.8.4

ingress:
  enabled: true
  annotations: {}
  spec:
    rules:
      - host: vault.does.not.exist
        http:
          paths:
          - backend:
              service:
                name: vault
                port:
                  number: 8200
            path: /
            pathType: ImplementationSpecific

istio:
  enabled: false

size: 1

auth:
  namespaces:
  - secret-infra

pvc:
  storageClassName:

# example "default"
customAuthRole: ""
